config/routes.rb
Bds::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
	
	namespace :admin do
		root :to => 'admin#index'
		resources :articles
	end

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, :type => String
  field :body, :type => String
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	before_filter :authenticate_user!
	
	def index
	end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
	def new
		@article = Article.new
	end

	def create
		@article = Article.create params[:article]
		respond_with :admin, @article, :location => root_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	respond_to :html, :json
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@articles = Article.all
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin/index.html.haml
=button_to "New Article", new_admin_article_path, :method => :get

app/views/admin/articles/new.html.haml
= form_for [:admin,@article] do |f|
	%p
		=f.text_field :title 
		=f.text_area :body
	%p
		=f.submit

app/views/home/index.html.haml
.row
  .three.columns.sondage.panel
    %h3 Sondage
    .question
      %h4 Question 1
      
    %form 
      %label{ :for => "id1"} Valeur 1
      %input{ :type => "checkbox", :value => "Valeur 1", :name => "id1"}
      %br
      %label{ :for => "id2"} Valeur 2
      %input{ :type => "checkbox", :value => "Valeur 2", :name => "id2"}
      %br
      %label{ :for => "id3"} Valeur 3
      %input{ :type => "checkbox", :value => "Valeur 3", :name => "id3"}
      
      %input{ :type => "submit", :value => "Je vote", :class => "nice small radius blue button"}
  .seven.columns.offset-by-one.article
    - @articles.each do |article|
      %article
        %h3.titre=article.title
        %p.contenu=article.body

app/views/layouts/application.haml
!!!
%html
  %head
    %title Bds
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .header
    
    %ul.topnav
      %li Lien 1
      %li Lien 2
      %li Lien 3
      
    .container
      = yield
    .footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bds
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .header
    
    %ul.topnav
      %li Lien 1
      %li Lien 2
      %li Lien 3
      
    .container
      = yield
    .footer